---
title: "\\emph{Synecdoche, New York}"
author: Mohamed Marhraoui
bibliography: bib.bib
csl: chicago/chicago-fullnote-bibliography-with-ibid.csl
output:
  pdf_document:
    number_sections: true
    latex_engine: xelatex
    toc: true
  html_document:
    toc: true
    toc_float: true
mainfont: Iosevka SS03
abstract: "This is my abstract.\\par \\textbf{Keywords:} Film Analysis"
header-includes:
    - \usepackage{setspace}
    - \doublespacing
indent: true
---

\pagebreak

# Introduction

After its premiere at the 61^st^ Annual Cannes Film Festival on May 23, 2008, with a running time of 124 minutes, Charlie Kaufman's directorial debut, _Synecdoche, New York_, triggered an ambivalent range of reviews. As The Observer's own Rex Reed writes: "no matter how bad you think the worst movie ever made ever was, you have not seen _Synecdoche, New York_," ^[@reed_2008.] Pulitzer Prize winner Roger Ebert declares _Synecdoche_ ^[_Synecdoche, New York_ will often be referred to as _Synecdoche_ throughout the paper.] film of the decade ^[@ebert_2009.]. The film has garnered a critics score of 68% and an audience score of 71% on Rotten Tomatoes ^[The critics score is also known as Tomatometer. See @rotten_tomatoes.], which illustrates a degree of polarization, perhaps best summarized in Peter Bradshaw's review ^[@bradshaw_2009.], where he states: "The film is either a masterpiece or a massively dysfunctional act of self-indulgence and self-laceration."

## Director

Charles Stuart Kaufman is an American screenwriter and director. Started as a television writer, Kaufman achieved critical acclaim and recognition for writing _Being John Malkovich_ ^[@jonze_1999.] and went on to be responsible for scripts of other distinguished films such as _Adaptation_ ^[@jonze_2002.] and _Eternal Sunshine of the Spotless Mind_ ^[@gondry_2004.], which earned him an Academy Award in 2004.

Kaufman is unique in that he is a screenwriter that is credited on an equal footing as the directors in his films if not slightly more. _Eternal Sunshine of the Spotless Mind_, for instance, is more regarded a "Charlie Kaufman film" than it is Michel Gondry's. Most people would have a hard time attributing Kaufman films to either Gondry or Spike Jonze, Kaufman's other lifelong collaborator. That goes to show how much of a distinctive voice he is in an increasingly non-reading world.

Kaufman's directorial debut, _Synecdoche, New York_, was largely unprofitable during its theatrical run, due to a globally crashing economy, generating a total of 4.47 million USD while having a production budget of 20 million USD ^[@box_office_mojo.]. Coupled with the fact that Charlie refuses to indulge in formulaic Hollywood screenwriting, _Synecdoche's_ financial failure set the ambitious now-director to a better part of a decade of stagnation.

## Synopsis

Summarizing _Synecdoche, New York_ without threading into the analysis is quite challenging as some scenes transform the plot under examination.

The story follows theater director Caden Cotard (Philip Seymour Hoffman). Aged 40, Caden is concerned with his health. "I don't feel well," ^[@kaufman_2008, 00:02:37.] he admits.

After a successful restaging of the play _Death of a Salesman_, Caden seeks validation from his wife, Adele (Catherine Keener), who is a painter of miniature art. Adele thinks very little of Caden's work, reproaching him for being a "tool" of regional theater. Later, she admits that she fantasizes about Caden's death to their therapist Madeleine (Hope Davis) to start a new life without guilt, which hurts Caden deeply.

Increasingly obsessed with his own mortality, Adele confronts Caden that she wants to go to Berlin for her show with just their 4 years of age daughter, Olive (Sadie Goldstein), leaving him for good. Devastated, Caden wipes Adele's painting studio clean and, later on, tries to reach her by phone, but she mistakes him for Ellen (Dianne Wiest), her cleaning lady, and, eventually, hangs up on him, after which, he goes into convulsions and struggles to call for emergency. At the hospital, Caden picks up a magazine that depicts Adele as a world-famous painter.

Subsequently, Hazel (Samantha Morton), the box office staff, attempts to have a relationship with Caden, but he ultimately rejects her out of his love for his family. Caden, then, receives a MacArthur Fellowship which he intends to use to create "something big and true and tough" and "finally put [his] real self into something" ^[@kaufman_2008, 00:36:55 -- 00:37:06.].

Filled with loneliness and regret, Caden tries to mend his relationship with Hazel but settles for Claire (Michelle Williams), an actress of his. Caden marries and has a daughter with Claire. He, then, becomes aware that his first daughter, Olive, at the age of 10, has a full-body tattoo and goes to Germany in search of her where he meets Maria (Jennifer Jason Leigh), Adele's best friend, who proclaims that she tattooed Olive. In continuous search of his daughter, Caden learns that Olive exhibits her body in a peep show to strangers. In a booth, Olive dances naked to her father, and he fails to get her attention and comes back empty-handed.

<!-- In a few years, Caden learns that Maria has become Olive's lover and that she -->

Caden's autobiographical play develops into a spatially impossible, mind-bending creation: an infinitely nested full-sized replica of New York City inside a warehouse.After getting fired from her job and in desperation, Hazel reconnects with Caden and takes the role of assistant in his play. Shortly after that, Sammy (Tom Noonan) auditions to play Caden and reveals that he has been following him for 20 years, and Caden agrees to cast him. Thereafter, Sammy hands Caden a slip of paper with Adele's address on it, and Caden goes there. In the hallway, Caden gets mistaken for Ellen, Adele's cleaning lady, and is given the keys to her apartment to clean it.

Informed by Maria, Caden meets Olive on her deathbed. She asks him to ask for forgiveness for abandoning her and for being a homosexual, which he does, but she is unable to forgive him and dies.

Back in the warehouse, Caden interviews Millicent Weems (Dianne Wiest ^[Dianne Wiest is credited both as Ellen Bascomb and Millicent Weems.]), and she gets to play the role of Ellen, the cleaning lady. Meanwhile, Sammy expresses that he likes Hazel, and she plays along with it, hoping to make Caden jealous. When Caden gets wind of this, he revives his relationship with Hazel by confessing his longing for her, leading to Sammy's suicide. The crew holds a funeral for him.

Old Caden and Hazel get together in her ever-burning, smoke-filled house and, they express feelings of yearning for one another and regret the wasted years. When Caden wakes up, he finds that Hazel died of smoke inhalation and determines that he will make the play about the day before she died as "it was the happiest day of [his] life. And [he'll] be able to relive it forever." ^[@kaufman_2008, 01:44:09 -- 01:44:40.]

Caden, now, remarks that he needs someone to play him. Millicent, who plays Ellen, steps up and convinces Caden to give her the role. At the rehearsal of Sammy's funeral's scene, Millicent, as the director, engages with the actors and gives them direct cues, and their performance impacts idle Caden emotionally. After Caden admits that he's out of ideas, Millicent suggests that she takes over him, temporarily, and he's cast to play Ellen in Millicent's stand as "[he does] like to clean" ^[@kaufman_2008, 01:49:59.].

At Millicent's direction, Caden puts on an earpiece that she uses to command every move of his. She instructs him to wipe himself, clean, walk, and have dreams. As he walks through abandoned, body-filled warehouse after warehouse, he meets Ellen's mother and apologizes for disappointing her terribly, and asserts that "[he] knows how to do the play now," ^[@kaufman_2008, 02:00:03.] and by Millicent's direction, he dies.

## Structure

Screenwriters often compare writing movie scripts to building houses, illustrating the need for a complete narrative and an easily identifiable conflict in the story. At a first glance, _Synecdoche, New York_ utilizes an internal Man versus Self conflict, but the case could be made for Man versus Nature and Man versus Fate conflicts (Caden's own ailments, decay, and eventual demise). These supposed conflicts are never overcome in the story, which, arguably, renders them less of literary elements and more of a byproduct of an honest account of a human life. Kaufman rejects

## Themes

The movie explores themes such as time, existentialism, solipsism, etc. However, the most prominent theme in the movie is death, even though the movie itself would disagree as Sammy, Caden's own doppelgänger, affirms that "This is not a play about dating. It's about death", to which Caden replies: "It is a play about dating. It's not a play just about death. It's about everything. Dating, birth, death, life, family. All that."

# Literature Review

Here goes the literature review.

# Analysis

Here goes the analysis.


# Conclusion

Here goes the conclusion.

\pagebreak

# Works Cited
